### ISSUE TITLE
port communication for real time emulation

### ISSUE THREAD

**Issue by josejimenezolivas** [josejimenezolivas/Micromouse_Simulator#55]

**Comment by jimenezjose** [comment]
Bidirectional serial communication via bluetooth - progress not started

**Comment by jimenezjose** [comment]
periscope feature is added. JComboBox listing all ports available to connect. Currently should only print the data received from serial ports. Also thinking whether this jcombobox should be permanent or only exists if for example the program is supplied with "solo mode" or "debug mode". For now, I left it rendering as a permanent change.

**Comment by jimenezjose** [comment]
Run Mode has merged with port communication.

**Comment by jimenezjose** [comment]
done
